### PR TITLE
migrate nisystemformat and nitargetinfo to OE

### PR DESCRIPTION
**Pull request by amstewart**
## nitargetinfo

`nitargetinfo` is a short script which uses `nisystemformat` to populate a sysapi property INI file under `/etc/natinst/share/`.

See justifications [here](https://dev.azure.com/ni/DevCentral/_git/ni-central/pullrequest/116920).

* The `nitargetinfo` script has been refreshed with a more condensed implementation, but is functionally the same.
* I have changed the runlevel from `20 5 .` to `20 S .`, since this script should start in all runlevels.

## nisystemformat

Migrate this utility to OE, since it is critical for many workflows. I created a new recipe for it: `ni-systemformat`. I'm not thrilled with that name; so feel free to push back on that.

`ni-systemformat` contains:
* The `nisystemformat` script, which is now installed to `/usr/bin` (away from `/usr/local/natinst/bin`).
* The `nitargetinfo` initscript.

The `nisystemformat` script is unchanged from its `nilrt_x64` equivalent, except that I have refreshed the "copyright". 

## testing

I have built `ni-systemformat` and confirmed on an x64 VM that it:
* installs `nisystemformat` to `/usr/bin/` w/ ownership=0:ni and mode=0550
    * it is present in $PATH
* installs `nitargetinfo` to `/etc/init.d/` and links to RL S at priority 20.
    * running the script generates the name `targetinfo.ini` file, with the correct vfs_types populated.

### CODE REVIEW

**Comment by amstewart** [comment]
@ni/rtos

**Comment by chaitu236** [comment]
Should this be added to nilrt-proprietary.inc?

**Comment by amstewart** [comment]
@chaitu236 
Ah yeah. Totally forgot about the packagegroup. I'll add it to one in V2.

**Comment by amstewart** [comment]
PATCH V2:
* add the `ni-systemformat` package to `packagegroup-ni-base`.

**Comment by chaitu236** [comment]
lgtm

**Pull request merged**
