### PR TITLE
Add rdma-core

### PR DESCRIPTION
**Pull request by rtollert**
Requested by @ericgrossNI.

Haven't tried building this yet — I just noticed it landed in meta-oe in dunfell.

### CODE REVIEW

**Comment by rtollert** [comment]
Oh good grief, my apologies. Apparently I meant to tag @ericgrossNI.

**Comment by egross** [comment]
It's all good :)

**Comment by shruthi-ravi** [comment]
Can you please add more context(why?) to the review as well as the commit?

**Comment by ericgross2** [comment]
See Azdo work item 1450565

**Comment by amstewart** [comment]
@rtollert We're going to schedule a meeting to speak more about when/how we want to distribute RDMA, with @ericgrossNI and co. So I'm going to hold off on pulling this PR until at least after that.

**Comment by rtollert** [comment]
I'll just leave this parked here then

**Comment by amstewart** [comment]
Seems like the RDMA implementation team is a ways away from actually needing this dep, and it isn't clear yet what mainline that will even go into. I'm going to close this PR for now (@rtollert) and let the implementation team open their own, when they get around to needing it.

**Comment by ericgross2** [comment]
Note: Were starting this work next month

**Pull request closed without merging**
