### PR TITLE
curl: Drop pharlap and nibuild specific commits

### PR DESCRIPTION
**Pull request by billpittman**
Drop the commits that specifically call out as being necessary for
pharlap or nibuild.  The commits that were upstreamed or marked as
necessary for other NI components were kept.

Signed-off-by: Bill Pittman <bill.pittman@ni.com>

### CODE REVIEW

**Review by amstewart — APPROVED** [review]
`~2100 lines removed` is what I like to see. :) I like this version of the patch much better; thanks.

Are you ready to merge?

**Comment by billpittman** [comment]
Yes just waiting for whoever wants to review it!

**Comment by amstewart** [comment]
OK. I'll pull it tomorrow then.

**Review by shruthi-ravi — APPROVED** [review]
Can you describe briefly why the nibuild and Win specific patches were dropped in the first commit description? Also, should we add Rich Tollerton as a reviewer so he can eyeball the dropped patches?

**Comment by billpittman** [comment]
On the first PR (that's now been closed/rejected), Alex pointed out that this curl component wouldn't be building for pharlap at all (since we're dropping Pharlap), and windows builds were pulling old exports of curl, so those aren't necessary anymore.

**Comment by shruthi-ravi** [comment]
Sorry I wasn't clear earlier. The commit message itself is missing this context, "the why". So, I was recommending that you add the reason to the commit message.

**Comment by billpittman** [comment]
Nope it was me, I went into explaining mode -- fixing it now!

**Comment by shruthi-ravi** [comment]
@rtollert can you take a look at this PR please?

**Comment by rtollert** [comment]
Approved.

**Pull request merged**
