### PR TITLE
Remove ti-wifi-utils as its ARM specific

### PR DESCRIPTION
**Pull request by chaitu236**
ti-wifi-utils is not compiling on hardknott.
But it's ARM specific so removing the recipe

@ni/rtos

### CODE REVIEW

**Review by shruthi-ravi — APPROVED** [review]
Can you add a note about the compilation issue to the commit message as well?

**Comment by chaitu236** [comment]
> Can you add a note about the compilation issue to the commit message as well?

Done

**Comment by amstewart** [comment]
If our intention is to not build it for any architecture, then lets also remove [the recipe](https://github.com/ni/meta-nilrt/tree/nilrt/master/sumo/recipes-connectivity/ti-wifi-utils) from the layer,  for cleanliness.

**Comment by chaitu236** [comment]
> If our intention is to not build it for any architecture, then lets also remove [the recipe](https://github.com/ni/meta-nilrt/tree/nilrt/master/sumo/recipes-connectivity/ti-wifi-utils) from the layer, for cleanliness.

Done

**Review by amstewart — APPROVED** [review]

**Pull request merged**
