### PR TITLE
[next] Subpackage consoleout sysconfig settings

### PR DESCRIPTION
**Pull request by amstewart**
### Summary of Changes

This patchset creates a new `sysconfig-settings-console` subpackage - similar to `sysconfig-settings-ui` - that subpackages the `consoleout` MAX toggles.

Unlike the `-ui` subpackage, this new one has not been removed from `packagegroup-ni-base` because I cannot justify a consoleless configuration as a conceptually distinct set. So the nilrt-snac configuration tool will just forcefully remove the `sysconfig-settings-console` package, instead of de-installing a packagegroup.

### Justification

The NILRT SNAC configuration disables consoleout by policy. This subpackage will let us remove the tempting MAX toggle to re-enable it. The toggle will still be present in safemode.

[AB#2769023](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2769023)

### Testing

* [x] I have built the base packagegroup with this change and tested its functionality on a NILRT VM.

### Procedure

* [x] I certify that the contents of this pull request complies with the [Developer Certificate of Origin](https://github.com/ni/nilrt/blob/HEAD/docs/CONTRIBUTING.md#developer-certificate-of-origin-dco).

### CODE REVIEW

**Review by chaitu236 — APPROVED** [review]
Changes look good.

We seem to have sysconfig-settings defined in packagegroup-ni-runmode and packagefeed-ni-extra as well which can probably be removed as packagegroup-ni-base already has it.

**Comment by amstewart** [comment]
> Changes look good.
> 
> We seem to have sysconfig-settings defined in packagegroup-ni-runmode and packagefeed-ni-extra as well which can probably be removed as packagegroup-ni-base already has it.

Since cleaning this up is going to take me a few hours of rebuilding the images, I'll just merge this commit without the cleanup and make a personal note to get around to it.

**Comment by gratian** [comment]
@amstewart Any reason why this had to be rushed in before the cleanup?

I don't like solutions like "I'll just merge this commit without the cleanup and make a personal note to get around to it".

**Comment by amstewart** [comment]
You know the cleanup we're talking about isn't related to this PR; right? It's some minor tech debt that has been in the packagegroup since 2021.

**Pull request merged**
