### PR TITLE
cherry-pick: remove meta-measured as it is dead upstream

### PR DESCRIPTION
**Pull request by ni-jxie**
Cherry-pick into the release branch.

### CODE REVIEW

**Comment by amstewart** [comment]
The `nilrt/21.8/hardknott` branch was forked prior to merging #355. So I think you will have to cherry-pick that patchset first.

@shruthi-ravi

**Comment by ni-jxie** [comment]
> 

Gotcha, #365

**Comment by shruthi-ravi** [comment]
Would a merge be easier if we want all the changes? @amstewart

**Comment by ni-jxie** [comment]
> > 
> 
> Gotcha, #365

**Comment by amstewart** [comment]
@shruthi-ravi Conceptually, I think our intention is to scrutinize PRs which are submitted against the release branches while we perform go-final. If we're attempting to exercise that workflow, then I think we need to hold ourselves to submitting cherry-pick PRs for content which needs to build during that period. So while it would be easier for you or I to submit a merge, I think it would be violating our own policies.

**Pull request merged**
