### PR TITLE
kernel-performace-tests: Update iperf server configuration

### PR DESCRIPTION
**Pull request by shruthi-ravi**
Update iperf server configuration to our new rack-mounted iperf server and port.

One less thing for dashboard to orchestrate if I hard code the server into the test configuration. I was thinking that we could start with this and then figure out a way for dashboard to pass this to the test.

### CODE REVIEW

**Review by amstewart — COMMENTED** [review]
What happens if someone from outside the corporate network runs this test without first modifying the configuration? Do they get some sort of sane error?

**Comment by shruthi-ravi** [comment]
@amstewart I've added some error checking to act nicely if the iperf connection cannot be made. Specifically, I'm skipping the test.

**Review by amstewart — APPROVED** [review]

**Review by amstewart — CHANGES_REQUESTED** [review]
[kernel-performace-tests: Update iperf server configuration](https://github.com/ni/meta-nilrt/pull/484/commits/22ea6df77a72cc0a0c0ff0eca12ffd4f94eb9dfc)

Commit summary spelling.

**Comment by shruthi-ravi** [comment]
v2: Fixed spelling in the first commit's summary.

**Review by amstewart — APPROVED** [review]

**Review by gratian — APPROVED** [review]

**Pull request merged**
