### PR TITLE
sumo: staple kernel versions for 2022Q3

### PR DESCRIPTION
**Pull request by shruthi-ravi**
### Testing
Built `linux-nilrt` and `linux-nilrt-debug`.

### CODE REVIEW

**Review by amstewart — APPROVED** [review]

**Review by gratian — CHANGES_REQUESTED** [review]
The commit stapling the revision for the kernel branch looks good and I approve.

However I am not sure removing the `nohz` and `next` packages is a good idea w/o removing all the references to them i.e. there's packagegroups and tests that refer to those recipes.

The `nohz` and `next` kernel variants are supported on Sumo for x64 targets and they are added to the `recipes-core/packagegroups/packagegroup-ni-desirable.bb` with `RDEPENDS_${PN}_append_x64 =`

Those recipes are only built (and fail) on ARM if you manually invoke bitbake directly on those recipes. If you do want to remove them because this branch is ARM only then I think you need to remove all the references to them too.

At this stage my recommendation is to leave them in place - they're not hurting anything for normal image builds.

**Comment by amstewart** [comment]
@shruthi-ravi Could you resubmit, only stapling the existing recipes.

**Comment by shruthi-ravi** [comment]
@amstewart do you want to staple the -next and -nohz recipes, or leave them as is?

**Comment by amstewart** [comment]
@shruthi-ravi Yeah; staple all of them.

**Review by amstewart — CHANGES_REQUESTED** [review]
You need to set the `NI_RELEASE_VERSION` variable to `22.5`, I think.

**Comment by shruthi-ravi** [comment]
### Update v2
Reverted the nohz and next kernel recipes' deletion. Stapled all the kernel recipes, including the linux-next and linux-nohz recipes.

**Comment by shruthi-ravi** [comment]
### Update v3

Set NI_RELEASE_VERSION in kernel recipes to 22.5.

**Review by amstewart — APPROVED** [review]

**Review by gratian — APPROVED** [review]

**Pull request merged**
