### PR TITLE
local.conf.sample: Do not parametrize BUILDNAME to prevent reproducibility errors

### PR DESCRIPTION
**Pull request by chaitu236**
Signed-off-by: Chaitanya Vadrevu <chaitanya.vadrevu@ni.com>

### CODE REVIEW

**Comment by amstewart** [comment]
Do you have commentary on why using the `MACHINE_ARCH` in the build name produces hash mismatch errors? It's value should never change over the course of an image build, so is the error spurious?

**Comment by chaitu236** [comment]
> TUNE_FEATURES{mx32} = UnsetAR${HOST_PREFIX}arARCH${@map_kernel_arch(d.getVar('TARGET_ARCH'), d)}AS${HOST_PREFIX}as ${HOST_AS_ARCH}ASNEEDED-Wl,--as-neededB${WORKDIR}/linux-${PACKAGE_ARCH}-${LINUX_KERNEL_TYPE}-buildBUILDNAMEdev-${**MACHIN  E_ARCH**}BUILD_AR

This is the log from the first time basehash is calculated - MACHINE_ARCH is not set by this time.
MACHINE_ARCH is set only in subsequent basehash calculations - it is not clear why this is the case though.

Replacing MACHINE_ARCH with other variables (like MACHINE) results in same behavior.

PS: This is not spurious and is always reproducible

**Comment by amstewart** [comment]
Huh. I suppose that explains why it doesn't recur on subsequent builds. OK. Ship it.

**Comment by amstewart** [comment]
@chaitu236 Could you submit a similar PR to the dunfell branch, when you're ready.

**Pull request merged**
