### PR TITLE
salt: Rework salt scripts' hashbang fixes 

### PR DESCRIPTION
**Pull request by shruthi-ravi**
This fixes azdo bug [1988577](https://ni.visualstudio.com/DevCentral/_workitems/edit/1988577).

### Testing
Verified that the salt-* files in the bitbake workspace usr/bin directory have the #!/usr/bin/python3 hashbang instead of #!/usr/bin/env python3. Also validated that a similar change on the target fixes the salt-minion init script.
The installer itself is more difficult to test, and will be validated in an exported image.

### CODE REVIEW

**Review by amstewart — CHANGES_REQUESTED** [review]
Changes look good. But it seems that one of the commit messages got truncated.

```
salt: add python3-core dependency

bitbake requires this dependency because the scripts have the

Signed-off-by: Shruthi Ravichandran <shruthi.ravichandran@ni.com>
```

**Comment by shruthi-ravi** [comment]
Weird. In both the commits, my references to `#!/usr/bin/python3` are messed up.

**Comment by shruthi-ravi** [comment]
Ohh. Maybe it's vim.

**Comment by shruthi-ravi** [comment]
#### Update v2:

Fix commit message references to the python hashbang.

**Review by amstewart — APPROVED** [review]

**Pull request merged**
