### PR TITLE
nilrt-desktop-background.jpg: Company Identity Updates

### PR DESCRIPTION
**Pull request by billpittman**
Update Embedded UI default background to reflect the
new company identity.

Signed-off-by: Bill Pittman <bill.pittman@ni.com>

### CODE REVIEW

**Comment by billpittman** [comment]
Attn: @ni/rtos

**Review by amstewart — APPROVED** [review]

**Comment by amstewart** [comment]
@gratian ?

**Review by gratian — APPROVED** [review]
There's a suggestion on the user story from the graphic designer to use .png instead of .jpg (for fewer artifacts) but I think we can commit this and handle the format change as a separate PR.

**Comment by billpittman** [comment]
Just pushed a new commit to change to PNG format both the xml file and the image file itself as per the request in the PR. @gratian and @amstewart I reset your reviews for the newest change to PNG.

**Review by gratian — APPROVED** [review]

**Comment by billpittman** [comment]
Updated commit with the PNG from Rick Ashby just to make sure we're using the "approved" PNG file.  Maintains quality control too since its all about Company Identity.

**Review by gratian — APPROVED** [review]

**Review by amstewart — APPROVED** [review]

**Comment by amstewart** [comment]
@billpittman Could you also put up a PR to pull this change into `nilrt/master/dunfell`?

**Pull request merged**
